### ISSUE TITLE
Ejecución de las pruebas

### ISSUE THREAD

**Issue by lauramcastro** [adrianudc/vvs#7]
A juzgar por el _log_ de la _build_ en Travis, no parece que las pruebas presentes en el repositorio se estén ejecutando.

**Comment by adrianudc** [comment]
Hola @lauramcastro.

En realidad sí se están ejecutando las pruebas, simplemente no se está mostrando el resultado de los tests satisfactorios en travis.

Voy a añadir una configuración en el fichero `build.gradle` para que se muestren los tests ejecutados, independientemente de su resultado.

Saludos¡
